module.exports = {
  v1: '/api/v1',
  API_NAME_RUNNING: 'API NAME is running on PORT',

  SUCCESS: 'success',
  FAIL: 'fail',
  THIRD_PARTY_ERROR: 'Error From Third Party Api',
  WELCOME: 'Welcome to heartbeat route ',
  INVALID_CREDENTIALS: 'Incorrect login details',
  INVALID_PERMISSION: 'Permission denied. Invalid credentials provided',
  USER_SIGNUP_SUCCESS: 'Account created successfully',
  MODULE_ERROR_STATUS: 'MODULE_PROCESS_BROKE',
  MODULE_ERROR: 'A module error occurred',
  DB_SUCCESS: 'Database connected',
  DB_ERROR_STATUS: 'DB_PROCESS_FAILED',
  DB_ERROR: 'A database error occurred',
  FORBIDDEN: 'Access forbidden. You do not have the required access.',

  NOT_ALLOWED: 'You are not allowed to perform this action',
  CREATE_USER_SUCCESS: 'Created user successfully',
  CAMPAIGN_CREATED: 'Campaign created successfully',
  USERNAME_ALREADY_EXIST: 'USERNAME exists already',
  USER_EXIST_VERIFICATION_FAIL: 'USER_EMAIL_EXIST_VERIFICATION_FAIL',
  USER_EMAIL_EXIST_VERIFICATION_FAIL: 'USER_EMAIL_EXIST_VERIFICATION_FAIL',
  USER_EMAIL_EXIST_VERIFICATION_FAIL_MSG:
    'Login failed. It is not you, it is us.',
  INTERNAL_SERVER_ERROR: 'Oops, something broke on the server!!!',
  LOGIN_USER_SUCCESSFULLY: 'Login Successful',
  INVALID_EMAIL: 'This email does not exist, please enter a registered email',
  USER_NOT_FOUND: 'User not found',
  ERROR_FETCHING_USER: 'Error fetching user',
  ERROR_VERIFYING_USER: 'ERROR VERIFYING USER',
  ERROR_VERIFYING_USER_MSG:
    'Error trying to verify user. It is not you, it is us.',
  NOT_FOUND_API: 'Oops, You have reached a dead end',
  ACCESS_REVOKED: 'ACCESS REVOKED',
  AUTH_REQUIRED: 'Access denied,a valid access token is required',
};
